spring:
  application:
    name: life-mind-account

  cloud:
    nacos:
      server-addr: 127.0.0.1:18848
      discovery:
        group: LIFE_MIND_GROUP
        ephemeral: false

      config:
        file-extension: yaml

  config:
    import:
      - nacos:redis.yaml?group=LIFE_MIND_CONFIG
      - nacos:account.yaml?group=LIFE_MIND_CONFIG
      - nacos:jwt_key.yaml?group=LIFE_MIND_CONFIG



