spring:
  application:
    name: life-mind-account

  cloud:
    nacos:
      server-addr: 127.0.0.1:18848
      discovery:
        group: ACCOUNT_GROUP
        ephemeral: false

      config:
        file-extension: yaml

  config:
    import:
      - nacos:redis.yaml?group=REDIS_CONFIG
      - nacos:account.yaml?group=ACCOUNT_CONFIG


